### ISSUE TITLE
Social Likes Next

### ISSUE THREAD

**Issue by sapegin** [sapegin/social-likes#149]
* No counters.
* No jQuery.
* IE10+.
* ES6 + Webpack / Rollup.
* No web fonts or PNGs (SVG icons).
* No classic skin.
* Tests.

No ETA, the code is [in a separate repository](https://github.com/sapegin/social-likes-next).

To do:

* [x] ES5 → ES6, jQuery → no jQuery.
* [x] Webpack JS build.
* [x] JSCS + JSHint → ESLint.
* [x] Skins build (Webpack?).
* [ ] New builder page.
* [ ] Autopublish builder page to gh-pages (gh-pages module).
* [x] Add tests.
* [x] Publish to npm.

Related issues: #136, #147, #119, #72, #67, #39.

**Comment by iamstarkov** [comment]
I can help you with autopublish page when you will be done with other stuff, ping me when my help will be required

**Comment by sapegin** [comment]
I did that before. But I have to update (most probably rewrite) a builder site first.

**Comment by sapegin** [comment]
:boom: [Social Likes Next 1.0.0 is out!](https://github.com/sapegin/social-likes-next/releases/tag/1.0.0) :boom:
